### ISSUE TITLE
Can you make it available for iOS?

### ISSUE THREAD

**Issue by nazar-41** [denisblondeau/TestVLCKIT#1]

**Comment by denisblondeau** [comment]
Very basic demo posted here: https://github.com/denisblondeau/TestVLCKitIOS

**Comment by denisblondeau** [comment]
Very basic demo posted here: https://github.com/denisblondeau/TestVLCKitIOS

**Comment by denisblondeau** [comment]
Very basic demo posted here: https://github.com/denisblondeau/TestVLCKitIOS
